#!/bin/bash
#
# Restic Agent Installation Script for Linux (systemd)
#
# This script installs the Restic backup agent as a systemd service.
# It creates necessary directories, configuration files, and sets up
# the agent to run automatically on system startup.
#
# Usage: sudo ./install.sh [OPTIONS]
#
# Options:
#   --orchestrator-url URL    Orchestrator server URL (required)
#   --auth-token TOKEN        Authentication token (required)
#   --agent-binary PATH       Path to agent binary (default: ./restic-agent)
#   --install-dir DIR         Installation directory (default: /usr/local/bin)
#   --config-dir DIR          Configuration directory (default: /etc/restic-agent)
#   --state-dir DIR           State directory (default: /var/lib/restic-agent)
#   --log-dir DIR             Log directory (default: /var/log/restic-agent)
#   --temp-dir DIR            Temp directory (default: /tmp/restic-agent)
#   --user USER               Service user (default: restic-agent)
#   --group GROUP             Service group (default: restic-agent)
#   --help                    Show this help message
#

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
ORCHESTRATOR_URL=""
AUTH_TOKEN=""
AGENT_BINARY="./restic-agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/restic-agent"
STATE_DIR="/var/lib/restic-agent"
LOG_DIR="/var/log/restic-agent"
TEMP_DIR="/tmp/restic-agent"
SERVICE_USER="restic-agent"
SERVICE_GROUP="restic-agent"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --orchestrator-url)
            ORCHESTRATOR_URL="$2"
            shift 2
            ;;
        --auth-token)
            AUTH_TOKEN="$2"
            shift 2
            ;;
        --agent-binary)
            AGENT_BINARY="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --config-dir)
            CONFIG_DIR="$2"
            shift 2
            ;;
        --state-dir)
            STATE_DIR="$2"
            shift 2
            ;;
        --log-dir)
            LOG_DIR="$2"
            shift 2
            ;;
        --temp-dir)
            TEMP_DIR="$2"
            shift 2
            ;;
        --user)
            SERVICE_USER="$2"
            shift 2
            ;;
        --group)
            SERVICE_GROUP="$2"
            shift 2
            ;;
        --help)
            sed -n '2,16p' "$0" | sed 's/^# //'
            exit 0
            ;;
        *)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Validation
if [ -z "$ORCHESTRATOR_URL" ]; then
    echo -e "${RED}Error: --orchestrator-url is required${NC}"
    exit 1
fi

if [ -z "$AUTH_TOKEN" ]; then
    echo -e "${RED}Error: --auth-token is required${NC}"
    exit 1
fi

if [ ! -f "$AGENT_BINARY" ]; then
    echo -e "${RED}Error: Agent binary not found: $AGENT_BINARY${NC}"
    exit 1
fi

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

echo -e "${GREEN}=== Restic Agent Installation ===${NC}"
echo ""

# Step 1: Create service user and group
echo -e "${YELLOW}[1/7] Creating service user and group...${NC}"
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /bin/false "$SERVICE_USER"
    echo "  Created user: $SERVICE_USER"
else
    echo "  User already exists: $SERVICE_USER"
fi

# Step 2: Create directories
echo -e "${YELLOW}[2/7] Creating directories...${NC}"
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"
mkdir -p "$STATE_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$TEMP_DIR"
echo "  Created: $INSTALL_DIR"
echo "  Created: $CONFIG_DIR"
echo "  Created: $STATE_DIR"
echo "  Created: $LOG_DIR"
echo "  Created: $TEMP_DIR"

# Step 3: Copy agent binary
echo -e "${YELLOW}[3/7] Installing agent binary...${NC}"
cp "$AGENT_BINARY" "$INSTALL_DIR/restic-agent"
chmod 755 "$INSTALL_DIR/restic-agent"
echo "  Installed: $INSTALL_DIR/restic-agent"

# Step 4: Create configuration file
echo -e "${YELLOW}[4/7] Creating configuration file...${NC}"
cat > "$CONFIG_DIR/agent.yaml" <<EOF
# Restic Agent Configuration
# Generated by install.sh on $(date)

# Required: Orchestrator server URL
orchestratorUrl: "$ORCHESTRATOR_URL"

# Required: Authentication token
authenticationToken: "$AUTH_TOKEN"

# Optional: Override system hostname
# hostnameOverride: "my-server"

# Optional: Log level (debug, info, warn, error)
logLevel: "info"

# Optional: Log file path (empty = stdout)
logFile: "$LOG_DIR/agent.log"

# Optional: Polling interval in seconds (5-3600)
pollingIntervalSeconds: 30

# Optional: Heartbeat interval in seconds (10-3600)
heartbeatIntervalSeconds: 60

# Optional: Maximum concurrent backup jobs (1-10)
maxConcurrentJobs: 2

# Optional: HTTP timeout in seconds (5-300)
httpTimeoutSeconds: 30

# Optional: Retry attempts for failed requests (0-10)
retryMaxAttempts: 3

# Optional: Retry backoff in seconds (1-60)
retryBackoffSeconds: 5

# Optional: State file path
stateFile: "$STATE_DIR/state.json"

# Optional: Temporary directory
tempDir: "$TEMP_DIR"
EOF

chmod 600 "$CONFIG_DIR/agent.yaml"
echo "  Created: $CONFIG_DIR/agent.yaml"

# Step 5: Set permissions
echo -e "${YELLOW}[5/7] Setting permissions...${NC}"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$CONFIG_DIR"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$STATE_DIR"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$LOG_DIR"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$TEMP_DIR"
echo "  Set ownership: $SERVICE_USER:$SERVICE_GROUP"

# Step 6: Create systemd service
echo -e "${YELLOW}[6/7] Creating systemd service...${NC}"
cat > /etc/systemd/system/restic-agent.service <<EOF
[Unit]
Description=Restic Backup Agent
Documentation=https://github.com/AlexRoehm/restic-monitor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_GROUP
ExecStart=$INSTALL_DIR/restic-agent --config $CONFIG_DIR/agent.yaml
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=restic-agent

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$STATE_DIR $LOG_DIR $TEMP_DIR

# Resource limits
LimitNOFILE=65536
LimitNPROC=512

[Install]
WantedBy=multi-user.target
EOF

echo "  Created: /etc/systemd/system/restic-agent.service"

# Step 7: Enable and start service
echo -e "${YELLOW}[7/7] Enabling and starting service...${NC}"
systemctl daemon-reload
systemctl enable restic-agent.service
systemctl start restic-agent.service
echo "  Service enabled and started"

# Check service status
echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo "Service status:"
systemctl status restic-agent.service --no-pager || true
echo ""
echo "Useful commands:"
echo "  View logs:       journalctl -u restic-agent.service -f"
echo "  Stop service:    sudo systemctl stop restic-agent.service"
echo "  Start service:   sudo systemctl start restic-agent.service"
echo "  Restart service: sudo systemctl restart restic-agent.service"
echo "  Check status:    sudo systemctl status restic-agent.service"
echo "  View config:     cat $CONFIG_DIR/agent.yaml"
echo "  View state:      cat $STATE_DIR/state.json"
echo ""
echo -e "${GREEN}Installation successful!${NC}"
