# Restic Agent Installation Script for Windows (Windows Service)
#
# This script installs the Restic backup agent as a Windows service.
# It creates necessary directories, configuration files, and sets up
# the agent to run automatically on system startup.
#
# Usage: .\install.ps1 [OPTIONS]
#
# Options:
#   -OrchestratorUrl URL      Orchestrator server URL (required)
#   -AuthToken TOKEN          Authentication token (required)
#   -AgentBinary PATH         Path to agent binary (default: .\restic-agent.exe)
#   -InstallDir DIR           Installation directory (default: C:\Program Files\ResticAgent)
#   -ConfigDir DIR            Configuration directory (default: C:\ProgramData\ResticAgent\config)
#   -StateDir DIR             State directory (default: C:\ProgramData\ResticAgent\state)
#   -LogDir DIR               Log directory (default: C:\ProgramData\ResticAgent\logs)
#   -TempDir DIR              Temp directory (default: C:\ProgramData\ResticAgent\temp)
#   -ServiceName NAME         Service name (default: ResticAgent)
#   -Help                     Show this help message
#

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$OrchestratorUrl,

    [Parameter(Mandatory=$true)]
    [string]$AuthToken,

    [Parameter(Mandatory=$false)]
    [string]$AgentBinary = ".\restic-agent.exe",

    [Parameter(Mandatory=$false)]
    [string]$InstallDir = "C:\Program Files\ResticAgent",

    [Parameter(Mandatory=$false)]
    [string]$ConfigDir = "C:\ProgramData\ResticAgent\config",

    [Parameter(Mandatory=$false)]
    [string]$StateDir = "C:\ProgramData\ResticAgent\state",

    [Parameter(Mandatory=$false)]
    [string]$LogDir = "C:\ProgramData\ResticAgent\logs",

    [Parameter(Mandatory=$false)]
    [string]$TempDir = "C:\ProgramData\ResticAgent\temp",

    [Parameter(Mandatory=$false)]
    [string]$ServiceName = "ResticAgent",

    [Parameter(Mandatory=$false)]
    [switch]$Help
)

# Show help if requested
if ($Help) {
    Get-Help $MyInvocation.MyCommand.Path -Detailed
    exit 0
}

# Require administrator privileges
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Error "This script must be run as Administrator. Right-click PowerShell and select 'Run as Administrator'."
    exit 1
}

# Validate agent binary exists
if (-not (Test-Path $AgentBinary)) {
    Write-Error "Agent binary not found: $AgentBinary"
    exit 1
}

# Helper function for colored output
function Write-ColorOutput {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Message,
        
        [Parameter(Mandatory=$false)]
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

Write-ColorOutput "=== Restic Agent Installation (Windows) ===" -Color Green
Write-Host ""

# Step 1: Create directories
Write-ColorOutput "[1/6] Creating directories..." -Color Yellow
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
New-Item -ItemType Directory -Force -Path $TempDir | Out-Null
Write-Host "  Created: $InstallDir"
Write-Host "  Created: $ConfigDir"
Write-Host "  Created: $StateDir"
Write-Host "  Created: $LogDir"
Write-Host "  Created: $TempDir"

# Step 2: Copy agent binary
Write-ColorOutput "[2/6] Installing agent binary..." -Color Yellow
$TargetBinary = Join-Path $InstallDir "restic-agent.exe"
Copy-Item $AgentBinary $TargetBinary -Force
Write-Host "  Installed: $TargetBinary"

# Step 3: Create configuration file
Write-ColorOutput "[3/6] Creating configuration file..." -Color Yellow
$ConfigFile = Join-Path $ConfigDir "agent.yaml"
$ConfigContent = @"
# Restic Agent Configuration
# Generated by install.ps1 on $(Get-Date)

# Required: Orchestrator server URL
orchestratorUrl: "$OrchestratorUrl"

# Required: Authentication token
authenticationToken: "$AuthToken"

# Optional: Override system hostname
# hostnameOverride: "my-windows-server"

# Optional: Log level (debug, info, warn, error)
logLevel: "info"

# Optional: Log file path (empty = stdout)
logFile: "$($LogDir -replace '\\', '/')/agent.log"

# Optional: Polling interval in seconds (5-3600)
pollingIntervalSeconds: 30

# Optional: Heartbeat interval in seconds (10-3600)
heartbeatIntervalSeconds: 60

# Optional: Maximum concurrent backup jobs (1-10)
maxConcurrentJobs: 2

# Optional: HTTP timeout in seconds (5-300)
httpTimeoutSeconds: 30

# Optional: Retry attempts for failed requests (0-10)
retryMaxAttempts: 3

# Optional: Retry backoff in seconds (1-60)
retryBackoffSeconds: 5

# Optional: State file path
stateFile: "$($StateDir -replace '\\', '/')/state.json"

# Optional: Temporary directory
tempDir: "$($TempDir -replace '\\', '/')"
"@

$ConfigContent | Out-File -FilePath $ConfigFile -Encoding UTF8
Write-Host "  Created: $ConfigFile"

# Step 4: Set permissions (restrict to Administrators and SYSTEM)
Write-ColorOutput "[4/6] Setting permissions..." -Color Yellow
$Acl = Get-Acl $ConfigDir
$Acl.SetAccessRuleProtection($true, $false)
$AdminRule = New-Object System.Security.AccessControl.FileSystemAccessRule("BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
$SystemRule = New-Object System.Security.AccessControl.FileSystemAccessRule("NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
$Acl.SetAccessRule($AdminRule)
$Acl.SetAccessRule($SystemRule)
Set-Acl $ConfigDir $Acl
Write-Host "  Set permissions: Administrators and SYSTEM only"

# Step 5: Create Windows service
Write-ColorOutput "[5/6] Creating Windows service..." -Color Yellow

# Check if service already exists
$ExistingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($ExistingService) {
    Write-Host "  Service already exists, stopping and removing..."
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    & sc.exe delete $ServiceName
    Start-Sleep -Seconds 2
}

# Create service using sc.exe
$BinaryPath = "`"$TargetBinary`" --config `"$ConfigFile`""
& sc.exe create $ServiceName binPath= $BinaryPath start= auto DisplayName= "Restic Backup Agent" | Out-Null
& sc.exe description $ServiceName "Automated backup agent for Restic orchestrator" | Out-Null

# Configure service recovery options (restart on failure)
& sc.exe failure $ServiceName reset= 86400 actions= restart/10000/restart/30000/restart/60000 | Out-Null

Write-Host "  Created service: $ServiceName"

# Step 6: Start service
Write-ColorOutput "[6/6] Starting service..." -Color Yellow
Start-Service -Name $ServiceName
Start-Sleep -Seconds 2
Write-Host "  Service started"

# Check service status
Write-Host ""
Write-ColorOutput "=== Installation Complete ===" -Color Green
Write-Host ""
Write-Host "Service status:"
$Service = Get-Service -Name $ServiceName
if ($Service.Status -eq "Running") {
    Write-ColorOutput "  ✓ Service is running" -Color Green
} else {
    Write-ColorOutput "  ⚠ Service status: $($Service.Status)" -Color Yellow
}

Write-Host ""
Write-Host "Useful commands:"
Write-Host "  View logs:       Get-Content '$LogDir\agent.log' -Tail 50 -Wait"
Write-Host "  Stop service:    Stop-Service -Name $ServiceName"
Write-Host "  Start service:   Start-Service -Name $ServiceName"
Write-Host "  Restart service: Restart-Service -Name $ServiceName"
Write-Host "  Check status:    Get-Service -Name $ServiceName"
Write-Host "  View config:     Get-Content '$ConfigFile'"
Write-Host "  View state:      Get-Content '$StateDir\state.json'"
Write-Host "  Uninstall:       .\uninstall.ps1"
Write-Host ""
Write-ColorOutput "Installation successful!" -Color Green
