#!/bin/bash
#
# Restic Agent Installation Script for macOS (launchd)
#
# This script installs the Restic backup agent as a launchd service.
# It creates necessary directories, configuration files, and sets up
# the agent to run automatically on system startup.
#
# Usage: sudo ./install.sh [OPTIONS]
#
# Options:
#   --orchestrator-url URL    Orchestrator server URL (required)
#   --auth-token TOKEN        Authentication token (required)
#   --agent-binary PATH       Path to agent binary (default: ./restic-agent)
#   --install-dir DIR         Installation directory (default: /usr/local/bin)
#   --config-dir DIR          Configuration directory (default: /usr/local/etc/restic-agent)
#   --state-dir DIR           State directory (default: /var/lib/restic-agent)
#   --log-dir DIR             Log directory (default: /var/log/restic-agent)
#   --temp-dir DIR            Temp directory (default: /tmp/restic-agent)
#   --user USER               Service user (default: current user)
#   --help                    Show this help message
#

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
ORCHESTRATOR_URL=""
AUTH_TOKEN=""
AGENT_BINARY="./restic-agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/usr/local/etc/restic-agent"
STATE_DIR="/var/lib/restic-agent"
LOG_DIR="/var/log/restic-agent"
TEMP_DIR="/tmp/restic-agent"
SERVICE_USER="$SUDO_USER"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --orchestrator-url)
            ORCHESTRATOR_URL="$2"
            shift 2
            ;;
        --auth-token)
            AUTH_TOKEN="$2"
            shift 2
            ;;
        --agent-binary)
            AGENT_BINARY="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --config-dir)
            CONFIG_DIR="$2"
            shift 2
            ;;
        --state-dir)
            STATE_DIR="$2"
            shift 2
            ;;
        --log-dir)
            LOG_DIR="$2"
            shift 2
            ;;
        --temp-dir)
            TEMP_DIR="$2"
            shift 2
            ;;
        --user)
            SERVICE_USER="$2"
            shift 2
            ;;
        --help)
            sed -n '2,15p' "$0" | sed 's/^# //'
            exit 0
            ;;
        *)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Validation
if [ -z "$ORCHESTRATOR_URL" ]; then
    echo -e "${RED}Error: --orchestrator-url is required${NC}"
    exit 1
fi

if [ -z "$AUTH_TOKEN" ]; then
    echo -e "${RED}Error: --auth-token is required${NC}"
    exit 1
fi

if [ ! -f "$AGENT_BINARY" ]; then
    echo -e "${RED}Error: Agent binary not found: $AGENT_BINARY${NC}"
    exit 1
fi

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Default to current user if not specified
if [ -z "$SERVICE_USER" ]; then
    SERVICE_USER=$(id -un)
fi

echo -e "${GREEN}=== Restic Agent Installation (macOS) ===${NC}"
echo ""

# Step 1: Create directories
echo -e "${YELLOW}[1/6] Creating directories...${NC}"
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"
mkdir -p "$STATE_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$TEMP_DIR"
echo "  Created: $INSTALL_DIR"
echo "  Created: $CONFIG_DIR"
echo "  Created: $STATE_DIR"
echo "  Created: $LOG_DIR"
echo "  Created: $TEMP_DIR"

# Step 2: Copy agent binary
echo -e "${YELLOW}[2/6] Installing agent binary...${NC}"
cp "$AGENT_BINARY" "$INSTALL_DIR/restic-agent"
chmod 755 "$INSTALL_DIR/restic-agent"
echo "  Installed: $INSTALL_DIR/restic-agent"

# Step 3: Create configuration file
echo -e "${YELLOW}[3/6] Creating configuration file...${NC}"
cat > "$CONFIG_DIR/agent.yaml" <<EOF
# Restic Agent Configuration
# Generated by install.sh on $(date)

# Required: Orchestrator server URL
orchestratorUrl: "$ORCHESTRATOR_URL"

# Required: Authentication token
authenticationToken: "$AUTH_TOKEN"

# Optional: Override system hostname
# hostnameOverride: "my-mac"

# Optional: Log level (debug, info, warn, error)
logLevel: "info"

# Optional: Log file path (empty = stdout)
logFile: "$LOG_DIR/agent.log"

# Optional: Polling interval in seconds (5-3600)
pollingIntervalSeconds: 30

# Optional: Heartbeat interval in seconds (10-3600)
heartbeatIntervalSeconds: 60

# Optional: Maximum concurrent backup jobs (1-10)
maxConcurrentJobs: 2

# Optional: HTTP timeout in seconds (5-300)
httpTimeoutSeconds: 30

# Optional: Retry attempts for failed requests (0-10)
retryMaxAttempts: 3

# Optional: Retry backoff in seconds (1-60)
retryBackoffSeconds: 5

# Optional: State file path
stateFile: "$STATE_DIR/state.json"

# Optional: Temporary directory
tempDir: "$TEMP_DIR"
EOF

chmod 600 "$CONFIG_DIR/agent.yaml"
echo "  Created: $CONFIG_DIR/agent.yaml"

# Step 4: Set permissions
echo -e "${YELLOW}[4/6] Setting permissions...${NC}"
chown -R "$SERVICE_USER:staff" "$CONFIG_DIR"
chown -R "$SERVICE_USER:staff" "$STATE_DIR"
chown -R "$SERVICE_USER:staff" "$LOG_DIR"
chown -R "$SERVICE_USER:staff" "$TEMP_DIR"
echo "  Set ownership: $SERVICE_USER:staff"

# Step 5: Create launchd plist
echo -e "${YELLOW}[5/6] Creating launchd service...${NC}"
PLIST_PATH="/Library/LaunchDaemons/com.restic.agent.plist"
cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.restic.agent</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>$INSTALL_DIR/restic-agent</string>
        <string>--config</string>
        <string>$CONFIG_DIR/agent.yaml</string>
    </array>
    
    <key>UserName</key>
    <string>$SERVICE_USER</string>
    
    <key>RunAtLoad</key>
    <true/>
    
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    
    <key>StandardOutPath</key>
    <string>$LOG_DIR/stdout.log</string>
    
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/stderr.log</string>
    
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    
    <key>WorkingDirectory</key>
    <string>$STATE_DIR</string>
    
    <key>ThrottleInterval</key>
    <integer>10</integer>
</dict>
</plist>
EOF

chmod 644 "$PLIST_PATH"
echo "  Created: $PLIST_PATH"

# Step 6: Load and start service
echo -e "${YELLOW}[6/6] Loading and starting service...${NC}"
launchctl load "$PLIST_PATH"
echo "  Service loaded and started"

# Wait a moment for service to start
sleep 2

# Check service status
echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo "Service status:"
if launchctl list | grep -q "com.restic.agent"; then
    echo -e "${GREEN}  ✓ Service is running${NC}"
else
    echo -e "${YELLOW}  ⚠ Service may not be running${NC}"
fi

echo ""
echo "Useful commands:"
echo "  View logs:       tail -f $LOG_DIR/agent.log"
echo "  View stdout:     tail -f $LOG_DIR/stdout.log"
echo "  View stderr:     tail -f $LOG_DIR/stderr.log"
echo "  Stop service:    sudo launchctl unload $PLIST_PATH"
echo "  Start service:   sudo launchctl load $PLIST_PATH"
echo "  Check status:    sudo launchctl list | grep restic"
echo "  View config:     cat $CONFIG_DIR/agent.yaml"
echo "  View state:      cat $STATE_DIR/state.json"
echo ""
echo -e "${GREEN}Installation successful!${NC}"
