// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/prune/{name}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Applies retention policy (restic forget) to remove old snapshots. Use \"all\" as the name to prune all targets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Prune snapshots for a target or all targets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the backup target or 'all' for all targets",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prune operation completed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Prune operation failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/snapshot/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the list of files contained in the specified snapshot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Snapshots"
                ],
                "summary": "Get file list for a specific snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snapshot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of files",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_api.fileResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Snapshot file list not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/snapshots/{name}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns list of all snapshots for the specified backup target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Snapshots"
                ],
                "summary": "Get snapshots for a specific backup target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the backup target",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of snapshots",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_api.snapshotResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current status of all configured backup targets including health, snapshot counts, and last check time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Get status of all backup targets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional filter by target name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Array of statuses when no name parameter",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_api.statusResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status/{name}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current status of a single backup target by name. Optionally check if the latest snapshot is younger than a specified age.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Get status of a specific backup target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the backup target",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum age in hours for the latest snapshot. If specified, health status will be true only if repository is healthy AND snapshot is younger than maxage hours",
                        "name": "maxage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with backup status",
                        "schema": {
                            "$ref": "#/definitions/internal_api.statusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid maxage parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/toggle/{name}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Toggles the disabled state of a backup target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "Enable or disable monitoring for a target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the backup target",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Target state toggled successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/unlock/{name}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes stale locks from a Restic repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Unlock a repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the backup target",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Repository unlocked successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Target not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unlock failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.fileResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "file.txt"
                },
                "path": {
                    "type": "string",
                    "example": "/home/user/documents/file.txt"
                },
                "size": {
                    "type": "integer",
                    "example": 2048
                },
                "type": {
                    "type": "string",
                    "example": "file"
                }
            }
        },
        "internal_api.snapshotResponse": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string",
                    "example": "myserver"
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "short_id": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time": {
                    "type": "string",
                    "example": "2025-11-23T14:30:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_api.statusResponse": {
            "type": "object",
            "properties": {
                "checkedAt": {
                    "type": "string",
                    "example": "2025-11-23T15:00:00Z"
                },
                "disabled": {
                    "type": "boolean",
                    "example": false
                },
                "fileCount": {
                    "type": "integer",
                    "example": 1234
                },
                "health": {
                    "type": "boolean",
                    "example": true
                },
                "latestBackup": {
                    "type": "string",
                    "example": "2025-11-23T14:30:00Z"
                },
                "latestSnapshotID": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "name": {
                    "type": "string",
                    "example": "home"
                },
                "snapshotCount": {
                    "type": "integer",
                    "example": 42
                },
                "statusMessage": {
                    "type": "string",
                    "example": "restic check succeeded"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Bearer token authentication using AUTH_TOKEN",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Backup status and health monitoring",
            "name": "Status"
        },
        {
            "description": "Snapshot information and file listings",
            "name": "Snapshots"
        },
        {
            "description": "Repository maintenance operations",
            "name": "Maintenance"
        },
        {
            "description": "Target configuration management",
            "name": "Configuration"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Restic Monitor API",
	Description:      "API for monitoring Restic backup repositories",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
